Настроил логику анкеты
fickt/tourist_routes_project pull request #22
Opened 2023-09-06 15:12 UTC by Xverlxrd

2023-09-06 17:11 UTC, ytpt commented on client/src/modules/profile/components/profile/Profile.tsx
Файл Profile.tsx:
1. Cntr+alt+L чтобы выровнять все отступы;
2. Ошибка никак не обрабатывается, а значит user не поймёт, что что-то не так;
3. У меня в планах вынести из авторизации (FormElem.tsx) error и loader  и сделать переиспользуемыми элементами и использовать их по всему проекту. Пока не реализовано, можно использовать из блока авторизации:  const loader = useAppSelector(authLoader); const error = useAppSelector(authError); и в jsx: {loader && <PreloaderCar/>} {!loader && (error && <ErrorMessage errorText={error}/>)}
4. Строки 28-30 можно сократить до data.data.length > 0 && dispatch(handleRecommended(false));
5. В строках 39-40 используется текст. Женя говорил такое выносить в constants;
6. В строках 47-49 можно убрать круглые скобки, т.к. элемент один и написать в одну строку
{!recommended && <CardListComponent spots={questArray}/>}

Файл QuestionsServise.ts:
1. В строке 3 ты импортируешь interface, а мы договаривались писать type;
2. По-моему не нужно дополнительно класть токен в заголовок к запросу, потому что в файле utils/api.ts у нас ко всем запросам уже кладётся token. Я в отзывах ничего не кладу, хотя token там требуется (reviewService.ts);
3. В строках 12, 19, 23 есть текст, Женя может сказать вынести его в constants;
4) Тоже нужно сделать Cntrl+alt+L т.к. в строке 12 { headers }, а в  19 {headers};

Файл type.ts:
1. Надо заменить interface на type;

Файл QuestionCard.tsx:
1. Про обработку ошибок я писала ранее;
2. Текст надо вынести в constants;
3. Я бы добавила отступ после export const QuestionCard = () => {
и перед useEffect;
4. В 7 строке импортируется interface вместо type;
5. В 26 строке я бы поставила пробел после isLiked
const handleAnswer = (isLiked: boolean) => {
6. Согласно code-style return должен отделяться от кода пустой строкой;
7. Может быть есть смысл вынести в отдельный компонент, не уверена
<div className={s.questionCard__btns}>
                    <DislikeIcon
                        onClick={() => handleAnswer(false)}
                        className={s.questionCard__dislike}
                    />
                    <Text>или</Text>
                    <LikeIcon
                        onClick={() => handleAnswer(true)}
                        className={s.questionCard__like}
                    />
                </div>

Файл styles.module.scss:
1.  По-моему, когда используешь переменную цвета, то можно удалять сам цвет в классе, вот так: background: var(--background-02);
2. У строк 32, 37 нет отступа от предыдущего стиля;

Файл QuestionsButtons.tsx:
1. Строка 17 лишний отступ;
2. Строка 18, я бы добавила отступы после if и до и после знака > вот так:
if (answers && answers.length > 0) {
3. Нет обработки ошибки, пользователь не узнает, если что-то не так
4. Перед return 2 отступа строки;
5. Готово и Позже можно вынести в constants;

Файл types.ts:
1. Используется interface вместо type;
2. Строка 5 нет ; после параметра;

Файл QuestionsPreview.tsx:
1. В строке 3 используются одинарные кавычки, по code-style мы используем двойные или обратные;
2. Перед export const QuestionsPreview = () => { я бы добавила пустую строку;
3. Строка 9 и 10 текст можно вынести в constants;
4. Cntr+alt+L чтобы выровнять все отступы;

Файл questions-preview/styles.module.scss:
1. я бы добавила отступ между стилями и ещё отступ тут перед фигурной скобкой .wrapper{

Всё вышенаписанное носит рекомендационный характер и может оспариваться:)

2023-09-06 17:12 UTC, ytpt commented on client/src/modules/profile/components/profile/Profile.tsx
> Файл Profile.tsx:
> 
> 1. Cntr+alt+L чтобы выровнять все отступы;
> 2. Ошибка никак не обрабатывается, а значит user не поймёт, что что-то не так;
> 3. У меня в планах вынести из авторизации (FormElem.tsx) error и loader  и сделать переиспользуемыми элементами и использовать их по всему проекту. Пока не реализовано, можно использовать из блока авторизации:  const loader = useAppSelector(authLoader); const error = useAppSelector(authError); и в jsx: {loader && } {!loader && (error && )}
> 4. Строки 28-30 можно сократить до data.data.length > 0 && dispatch(handleRecommended(false));
> 5. В строках 39-40 используется текст. Женя говорил такое выносить в constants;
> 6. В строках 47-49 можно убрать круглые скобки, т.к. элемент один и написать в одну строку
>    {!recommended && }
> 
> Файл QuestionsServise.ts:
> 
> 1. В строке 3 ты импортируешь interface, а мы договаривались писать type;
> 2. По-моему не нужно дополнительно класть токен в заголовок к запросу, потому что в файле utils/api.ts у нас ко всем запросам уже кладётся token. Я в отзывах ничего не кладу, хотя token там требуется (reviewService.ts);
> 3. В строках 12, 19, 23 есть текст, Женя может сказать вынести его в constants;
> 
> 4. Тоже нужно сделать Cntrl+alt+L т.к. в строке 12 { headers }, а в  19 {headers};
> 
> Файл type.ts:
> 
> 1. Надо заменить interface на type;
> 
> Файл QuestionCard.tsx:
> 
> 1. Про обработку ошибок я писала ранее;
> 2. Текст надо вынести в constants;
> 3. Я бы добавила отступ после export const QuestionCard = () => {
>    и перед useEffect;
> 4. В 7 строке импортируется interface вместо type;
> 5. В 26 строке я бы поставила пробел после isLiked
>    const handleAnswer = (isLiked: boolean) => {
> 6. Согласно code-style return должен отделяться от кода пустой строкой;
> 7. Может быть есть смысл вынести в отдельный компонент, не уверена
> 
> handleAnswer(false)} className={s.questionCard__dislike} /> или handleAnswer(true)} className={s.questionCard__like} />
> Файл styles.module.scss:
> 
> 1. По-моему, когда используешь переменную цвета, то можно удалять сам цвет в классе, вот так: background: var(--background-02);
> 2. У строк 32, 37 нет отступа от предыдущего стиля;
> 
> Файл QuestionsButtons.tsx:
> 
> 1. Строка 17 лишний отступ;
> 2. Строка 18, я бы добавила отступы после if и до и после знака > вот так:
>    if (answers && answers.length > 0) {
> 3. Нет обработки ошибки, пользователь не узнает, если что-то не так
> 4. Перед return 2 отступа строки;
> 5. Готово и Позже можно вынести в constants;
> 
> Файл types.ts:
> 
> 1. Используется interface вместо type;
> 2. Строка 5 нет ; после параметра;
> 
> Файл QuestionsPreview.tsx:
> 
> 1. В строке 3 используются одинарные кавычки, по code-style мы используем двойные или обратные;
> 2. Перед export const QuestionsPreview = () => { я бы добавила пустую строку;
> 3. Строка 9 и 10 текст можно вынести в constants;
> 4. Cntr+alt+L чтобы выровнять все отступы;
> 
> Файл questions-preview/styles.module.scss:
> 
> 1. я бы добавила отступ между стилями и ещё отступ тут перед фигурной скобкой .wrapper{
> 
> Всё вышенаписанное носит рекомендационный характер и может оспариваться:)

2023-09-06 17:19 UTC, ytpt requested changes
Файл Profile.tsx:

1. Cntr+alt+L чтобы выровнять все отступы;
2. Ошибка никак не обрабатывается, а значит user не поймёт, что что-то не так;
3. У меня в планах вынести из авторизации (FormElem.tsx) error и loader и сделать переиспользуемыми элементами и использовать их по всему проекту. Пока не реализовано, можно использовать из блока авторизации: const loader = useAppSelector(authLoader); const error = useAppSelector(authError); и в jsx: {loader && } {!loader && (error && )}
4. Строки 28-30 можно сократить до data.data.length > 0 && dispatch(handleRecommended(false));
5. В строках 39-40 используется текст. Женя говорил такое выносить в constants;
6. В строках 47-49 можно убрать круглые скобки, т.к. элемент один и написать в одну строку
{!recommended && }

Файл QuestionsServise.ts:
1. В строке 3 ты импортируешь interface, а мы договаривались писать type;
2. По-моему не нужно дополнительно класть токен в заголовок к запросу, потому что в файле utils/api.ts у нас ко всем запросам уже кладётся token. Я в отзывах ничего не кладу, хотя token там требуется (reviewService.ts);
3. В строках 12, 19, 23 есть текст, Женя может сказать вынести его в constants;
4. Тоже нужно сделать Cntrl+alt+L т.к. в строке 12 { headers }, а в 19 {headers};

Файл type.ts:
1. Надо заменить interface на type;

Файл QuestionCard.tsx:
1. Про обработку ошибок я писала ранее;
2. Текст надо вынести в constants;
3. Я бы добавила отступ после export const QuestionCard = () => {
и перед useEffect;
4. В 7 строке импортируется interface вместо type;
5. В 26 строке я бы поставила пробел после isLiked
const handleAnswer = (isLiked: boolean) => {
6. Согласно code-style return должен отделяться от кода пустой строкой;
7. Может быть есть смысл вынести в отдельный компонент, не уверена
handleAnswer(false)} className={s.questionCard__dislike} /> или handleAnswer(true)} className={s.questionCard__like} />

Файл styles.module.scss:
1. По-моему, когда используешь переменную цвета, то можно удалять сам цвет в классе, вот так: background: var(--background-02);
2. У строк 32, 37 нет отступа от предыдущего стиля;

Файл QuestionsButtons.tsx:
1. Строка 17 лишний отступ;
2. Строка 18, я бы добавила отступы после if и до и после знака > вот так:
if (answers && answers.length > 0) {
3. Нет обработки ошибки, пользователь не узнает, если что-то не так
4. Перед return 2 отступа строки;
5. Готово и Позже можно вынести в constants;

Файл types.ts:
1. Используется interface вместо type;
2. Строка 5 нет ; после параметра;

Файл QuestionsPreview.tsx:
1. В строке 3 используются одинарные кавычки, по code-style мы используем двойные или обратные;
2. Перед export const QuestionsPreview = () => { я бы добавила пустую строку;
3. Строка 9 и 10 текст можно вынести в constants;
4. Cntr+alt+L чтобы выровнять все отступы;

Файл questions-preview/styles.module.scss:
1. я бы добавила отступ между стилями и ещё отступ тут перед фигурной скобкой .wrapper{



Всё вышенаписанное носит рекомендационный характер и может оспариваться:)

2023-09-06 17:24 UTC, DasGift commented on client/src/modules/profile/components/profile/Profile.tsx
> +import {Button} from "ui/button/Button";
вот тут типа ошибка

2023-09-07 04:27 UTC, ytpt commented on client/src/modules/profile/components/profile/Profile.tsx
> +                <ProfileSection path={RoutePath.mySpots} title={profileValues.plases}/>
грамматическая ошибка в слове places

2023-09-07 04:27 UTC, ytpt commented on client/src/modules/profile/constants/profileValues.ts
> +    plases: "Мои места",
грамматическая ошибка в слове places

2023-09-07 04:28 UTC, ytpt commented on client/src/modules/questions/api/type.ts
> +export type IAnswers = {
наименование типа тоже нужно изменить на TAnswers

2023-09-07 04:29 UTC, ytpt commented on client/src/modules/questions/components/question-card/QuestionCard.tsx
> +                dispatch(handleAuthError('Ошибка получения данных для анкеты'))
Одинарные кавычки нужно заменить на двойные

2023-09-07 04:29 UTC, ytpt commented on client/src/modules/questions/components/question-card/QuestionCard.tsx
> +                    <img className={s.questionCard__image} src={questions[questionIndex]} alt='Question Image'/>
Тут тоже одинарные кавычки

2023-09-07 04:30 UTC, ytpt commented on client/src/modules/questions/components/questions-buttons/QuestionsButtons.tsx
> +                    dispatch(handleAuthError('Ошибка отправки ответов на сервер'))
И тут кавычки

2023-09-07 04:31 UTC, ytpt commented on client/src/modules/questions/components/questions-preview/QuestionsPreview.tsx
> +            <p className={s.preview__text}>Для того чтобы сгенерировать персональные рекомендации, пройдите
Длинный текст Женя 100% попросит убрать в constants

2023-09-07 04:32 UTC, ytpt requested changes
Ещё чуть-чуть по код-стайлу

2023-09-07 06:33 UTC, merged